### ISSUE TITLE
Edit README.md file

### ISSUE THREAD

**Issue by KartikKannapur** [Sreevatsa123/index.html#3]
A README.md file should contain information about your repo/project, not the code. Edit accordingly.

**Comment by Sreevatsa123** [comment]
hey.i have changed accordingly.

**Comment by KartikKannapur** [comment]
Please refer to the documentation by other groups in GSC-RNSIT and follow the same pattern.

**Comment by Sreevatsa123** [comment]
I have done the changes accordingly.Please look into it.

**Comment by KartikKannapur** [comment]
Please do the same in all the branches.

**Comment by Sreevatsa123** [comment]
Done :)
